### ISSUE TITLE
Packagist registry is outdated

### ISSUE THREAD

**Issue by flavioheleno** [nilportugues/repository#16]
There is a new package version [3.1.0](https://github.com/PHPRepository/repository/releases/tag/3.1.0) but [Packagist](https://packagist.org/packages/nilportugues/repository) still refers to [3.0.2](https://packagist.org/packages/nilportugues/repository#3.0.2).

Can it be updated? I'm working on extending `null()` and `notNull()` filters to [sql-repository](https://github.com/PHPRepository/sql-repository) but I can't bump composer requirements (`dev-master` is also outdated).

Thanks :-)

**Comment by nilportugues** [comment]
I still need to add the null filters to sql-repository, that's why it's still not using 3.1.0

**Comment by flavioheleno** [comment]
I get your point, but I'm not sure if that's the best way to manage dependencies across the projects.

Either way, thanks :-)

**Comment by nilportugues** [comment]
@flavioheleno give me a bit and I'll update the dependency

**Comment by nilportugues** [comment]
Upped the version for sql-repository (minor). Now includes the updated dependency.
